language: generic

dist: xenial
sudo: false

services:
  - docker

script:
  #  - npm run lint
  # - npm run test:headless
  #- npm run build
  #- xvfb-run npm run e2e
  - docker build -t clientpanel:$TRAVIS_BRANCH-SNAPSHOT-$TRAVIS_BUILD_NUMBER .
