language: node_js
node_js:
  - '8'
dist: xenial
sudo: false

services:
  - docker

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  #  - npm run lint
  # - npm run test:headless
  #- npm run build
  #- xvfb-run npm run e2e
  - docker build -t clientpanel:1_0-SNAPSHOT .
