language: generic
dist: xenial
sudo: false
services:
  - docker
script:
  #- docker build -t clientpanel:latest -t clientpanel:$TRAVIS_BRANCH-SNAPSHOT-$TRAVIS_BUILD_NUMBER .
  #- echo "$TREESCALE_PASS" | docker login -u "$TREESCALE_USER" --password-stdin repo.treescale.com
  - docker login -u $TREESCALE_USER -p $TREESCALE_PASS repo.treescale.com
  - docker build -t clientpanel:latest -t clientpanel:$TRAVIS_BRANCH-SNAPSHOT-$TRAVIS_BUILD_NUMBER .
  - docker push repo.treescale.com/$TREESCALE_USER/clientpanel:$TRAVIS_BRANCH-SNAPSHOT-$TRAVIS_BUILD_NUMBER
  - docker logout repo.treescale.com
