language: generic
dist: xenial
sudo: false
services:
  - docker
script:
  - docker build -t clientpanel:latest -t clientpanel:$TRAVIS_BRANCH-SNAPSHOT-$TRAVIS_BUILD_NUMBER .
  - echo "$TREESCALE_USER"
  - echo $TREESCALE_USER
  - echo "$TREESCALE_PASS" | docker login -u "$TREESCALE_USER" --password-stdin repo.treescale.com
env:
  global:
    - secure: H10NpapN3yXwbpe2E4DzLavYHzYAUKyWcsZTD+Eke+pEiG9/YoeUs5K7EwTBhJI89ZVLMeAoNIfZowX2GnQXVyTEe288VRBWh0sCCW/LFUzWxzjEtjFeWGS0F8jdBIHzvyZINzdVop5yHz6lI1PEaFZeRQjc0DvHxHak+DaUKgauxQol7rlB5v5S+ZA3onZnWkpaY6P9mQ0zWoTg7qgA3iRM4m12bQuwkw1fVSj6S+nHC2v+lurPpjW9VEug9+GpTTc2z+njs1p93nPZYHyQZqtZdWhl18UAAgcDQz0x7jTLLs/nejPXH4ZS+9MmhWgSzfExDDHap2C5dollUQmR01nnUlvNTh3M7NsdSf/NMi3LcoT9IFyy4BLPIJvYM6qMrgEcFVei60YGqNHgkvv+4R6LiWy5t6BfHn5gvsGKW/EtMrZOadHEBm2I9xRIanO2Fy/xNbmTr5XBUhBIy23LQ+0kkgd4HrqxGgRjV5oKeerXqF2oFS6E+XY8M5ekw4L8Wr0VGPn16dxxFk7EaCgVoX9hk8NEvN+SCaiZ7R85zMPov0flaRAz+uVqRu18l1PpiRyvpN+65OSs1jHZ6CyxKe+fLsIBKGz+HZ3GWwGGw029OfbFDUiFPrdlbCX6FeNbs5NBEMgEIPltU0BSE9dVkpomE8Ym+T9f8tp3t0sOPGA=
    - secure: jSRh4lfXY9O8JmK/OsQU/JmORH1bkGZrCWsbPzyhoFDHbn8cPZ+axcMi8S1nhGNySwlRnzYmpgdbBZ58ft5AbMjcgTkZfPB1Yoe2S4OjhJBTq7h2Tp7bSfqyAIHosIajD69w0uTEdoFQ9TztH4YQPioM+9u9pfQiFFd6xyMPKphegDJMiWmRUI9fCnTgc/9bU8OQ+W/uEqAbdkp9Lrp+Hq2SD9HrZBa+/0P8/2YNh0ycoFTBL8tUTW3cHP8hI5Zop0fZtDgUaphttYTIfMWQakuzt9XtZi7bn/AKxgGMb/Yku0BlQjKWaRRwQ1OCnuBTgR8I+nGNL3ZbRlN9hHxKWNgwTvvnUO+A/WhjC3SrkGprmYvdEe8a65Zety7LwNl6osBK/Erymam2vCMA0+866d/iW9tszzCTJX4g0ZTVecbWYWEKESr4VUmFDTeAqaQAjy0/pAB8tATh4U7jgswZqtcmAScmcd7pTJXrJTKCEJPBrZINHpySygPDln9CN5dugPNlBddoQe31Df8agerEMBKYwd7+z72sLxv5DtAGvYUjTWHXIb5xdKpJOBAcwKvXhAlxZTbDR6jM8O6BV+D7luzgGgWp5xA0LwL4plqswTxXbam4Rm+IsIfoowJ/3aimOSC75hW9cn0gwErTwLYaIQzd5uL4eHxjb2oBrJ4EXS8=
